spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3307/photoapi
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
